### ISSUE TITLE
 Error: Please follow the steps correctly. Not authenticated

### ISSUE THREAD

**Issue by Wapweb** [aDarkDev/NotPixel#10]
After running 10-20 minutes I am getting error
```
[!] main: No charge available. Sleeping for 10 minutes...
[!] Requester: ConnectionError /mining/status. Sleeping for 5s...
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/home/user/NotPixel/main.py", line 179, in painter
    charges = NotPxClient.accountStatus()
  File "/home/user/NotPixel/main.py", line 108, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
  File "/home/user/NotPixel/main.py", line 62, in request
    raise Exception(authenticate_error)
Exception: Please follow the steps correctly. Not authenticated.
```

**Comment by aDarkDev** [comment]
> ConnectionError

You're connection is not stable
