### ISSUE TITLE
crash program

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#23]
after few minuts program crash:

Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\saleh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\test.py", line 190, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\test.py", line 115, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\test.py", line 63, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\test.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saleh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\telethon\sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\saleh\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.
C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py:1077: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

**Comment by mahdi429** [comment]
I have the same problem, how can I fix it?

**Comment by aDarkDev** [comment]
install telethon 1.35.0
```bash
pip3 install telethon==1.35.0
```
