### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by mahdi429** [aDarkDev/NotPixel#24]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\dev\python\workspace\NotPixel-main\main.py", line 174, in painter
    balance = NotPxClient.autoPaintPixel()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\dev\python\workspace\NotPixel-main\main.py", line 102, in autoPaintPixel
    return self.request("post","/repaint/start","balance",data)['balance']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by aDarkDev** [comment]
use latest version
