### ISSUE TITLE
terminal problem

### ISSUE THREAD

**Issue by AliCybeRR** [aDarkDev/NotPixel#30]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.
/usr/lib/python3.11/threading.py:1047: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Exception in thread Thread-3 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3 (painter)'.
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-5 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5 (painter)'.
Exception in thread Thread-7 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-7 (painter)'.
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-9 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-9 (painter)'.
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-11 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-11 (painter)'.
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-13 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-13 (painter)'.
^CException ignored in: <module 'threading' from '/usr/lib/python3.11/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1590, in _shutdown
    lock.acquire()
KeyboardInterrupt:

**Comment by aDarkDev** [comment]
install telethon 1.35.0
```bash
pip3 install telethon==1.35.0
```
