### ISSUE TITLE
Terminal error

### ISSUE THREAD

**Issue by boostrapz** [aDarkDev/NotPixel#35]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Admin\Desktop\notpixel-master\NotPixel-main\main.py", line 164, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\notpixel-master\NotPixel-main\main.py", line 93, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\notpixel-master\NotPixel-main\main.py", line 72, in request
    WebAppQuery = GetWebAppData(self.client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\Desktop\notpixel-master\NotPixel-main\main.py", line 16, in GetWebAppData
    notcoin = client.get_entity("notpixel")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\sync.py", line 35, in syncified
    loop = helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.
C:\Users\Admin\AppData\Local\Programs\Python\Python312\Lib\threading.py:1077: RuntimeWarning: coroutine 'UserMethods.get_entity' was never awaited
  self._invoke_excepthook(self)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

It's after installing telethon 1.35 as well

**Comment by mahdi429** [comment]
I have the same problem, how can I fix it?

**Comment by boostrapz** [comment]
> I have the same problem, how can I fix it?

dev said install telethon 1.35 but not helped to me

**Comment by aDarkDev** [comment]
i will fix it in update 1.6.1.

**Comment by aDarkDev** [comment]
> > I have the same problem, how can I fix it?
> 
> dev said install telethon 1.35 but not helped to me

https://github.com/aDarkDev/NotPixel/commit/823385d4e5403b5b9e462f0d3394dace79ad8bd0
use latest
