### ISSUE TITLE
using telethon==1.35.0 && using last update but this problem in termux/kali/arch/ubuntu

### ISSUE THREAD

**Issue by AliCybeRR** [aDarkDev/NotPixel#37]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-9 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-11 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-13 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
Exception in thread Thread-3 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-5 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-7 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined

**Comment by mahdi429** [comment]
I have the same problem

**Comment by aDarkDev** [comment]
use latest again. thanks for reporting
