### ISSUE TITLE
after modify

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#40]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "main.py", line 161, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 68, in request
    WebAppQuery = client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^
NameError: name 'client' is not defined. Did you mean: 'self.client'?

**Comment by aDarkDev** [comment]
oh, i will fix it now

**Comment by aDarkDev** [comment]
30108833fec3c25128b4341c9d3a112e3626693d
