### ISSUE TITLE
Exception in thread Thread

### ISSUE THREAD

**Issue by mahdi429** [aDarkDev/NotPixel#44]
After the new update, I have the previous error again
Thanks for solving the problem

Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mahdi\NotPixel\main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\client\telegrambaseclient.py", line 487, in loop
    return helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.
[!] Timeout Error /mining/status. Sleeping for 5s...
Exception in thread Thread-3 (painter):
Traceback (most recent call last):
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mahdi\NotPixel\main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\client\telegrambaseclient.py", line 487, in loop
    return helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-3 (painter)'.
Exception in thread Thread-5 (painter):
Traceback (most recent call last):
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Mahdi\NotPixel\main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\client\telegrambaseclient.py", line 487, in loop
    return helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\NotPixel\venv\Lib\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mahdi\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-5 (painter)'.

**Comment by aDarkDev** [comment]
1d45225011df8a2bb6c1dab725b6c4ce4e620024
