### ISSUE TITLE
new problem bro 

### ISSUE THREAD

**Issue by AliCybeRR** [aDarkDev/NotPixel#46]
[!] ConnectionError /mining/status. Sleeping for 5s...
[proxychains] Strict chain  ...  127.0.0.1:9050  ...  notpx.app:443  ...  OK
Exception in thread Thread-12 (mine_claimer):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 209, in mine_claimer
    acc_data = NotPxClient.accountStatus()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 486, in loop
    return helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-12 (mine_claimer)'.
Exception in thread Thread-11 (painter):
Traceback (most recent call last):
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 160, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/client/telegrambaseclient.py", line 486, in loop
    return helpers.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/.local/lib/python3.11/site-packages/telethon/helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/events.py", line 681, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-11 (painter)'.

**Comment by aDarkDev** [comment]
It will be solved tonight

**Comment by AliCybeRR** [comment]
pls give me your telegram id

**Comment by aDarkDev** [comment]
1d45225011df8a2bb6c1dab725b6c4ce4e620024
