### ISSUE TITLE
again after update

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#48]
again after update
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "telethon\helpers.py", line 430, in get_running_loop
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "threading.py", line 1075, in _bootstrap_inner
  File "threading.py", line 1012, in run
  File "main.py", line 161, in painter
    charges = NotPxClient.accountStatus()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 89, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "main.py", line 68, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
                  ^^^^^^^^^^^^^^^^
  File "telethon\client\telegrambaseclient.py", line 487, in loop
  File "telethon\helpers.py", line 432, in get_running_loop
  File "asyncio\events.py", line 702, in get_event_loop
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.

**Comment by aDarkDev** [comment]
1d45225011df8a2bb6c1dab725b6c4ce4e620024
