### ISSUE TITLE
Authentication renewed

### ISSUE THREAD

**Issue by mollyxs** [aDarkDev/NotPixel#50]
![image](https://github.com/user-attachments/assets/0d056a80-d2a5-483d-b02d-a0d28639dbe2)

Some time after “Authentication renewed” displayed this:

```
[+] Authentication renewed!
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1016, in _bootstrap_inner    self.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 166, in painter
    charges = NotPxClient.accountStatus()
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 95, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 77, in request
    return self.request(method, end_point, key_check, data)
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 77, in request
    return self.request(method, end_point, key_check, data)
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 77, in request
    return self.request(method, end_point, key_check, data)
  [Previous line repeated 967 more times]
  File "c:\Users\Administrator\Downloads\NotPixel-main\main.py", line 72, in request
    client = TelegramClient(self.session_name,api_id,api_hash,loop=nloop).start()
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\client\auth.py", line 128, in start
    else self.loop.run_until_complete(coro)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\client\auth.py", line 135, in _start
    await self.connect()
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\client\telegrambaseclient.py", line 548, in connect
    if not await self._sender.connect(self._connection(
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\network\mtprotosender.py", line 134, in connect
    await self._connect()
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\network\mtprotosender.py", line 234, in _connect
    connected = await self._try_connect(attempt)
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\network\mtprotosender.py", line 284, in _try_connect
    await self._connection.connect(timeout=self._connect_timeout)
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\network\connection\connection.py", line 250, in connect
    await self._connect(timeout=timeout, ssl=ssl)
  File "c:\Users\Administrator\Downloads\NotPixel-main\venv\lib\site-packages\telethon\network\connection\connection.py", line 222, in _connect
    self._reader, self._writer = await asyncio.wait_for(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 426, in wait_for
    fut = ensure_future(fut, loop=loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 615, in ensure_future    return _ensure_future(coro_or_future, loop=loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\tasks.py", line 636, in _ensure_future
    return loop.create_task(coro_or_future)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 438, in create_task
    task = tasks.Task(coro, loop=self, name=name)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 757, in call_soon
    handle = self._call_soon(callback, args, context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 773, in _call_soon
    handle = events.Handle(callback, args, self, context)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 40, in __init__
    if self._loop.get_debug():
RecursionError: maximum recursion depth exceeded
```

**Comment by whyte322** [comment]
same here

**Comment by aDarkDev** [comment]
a7947c3847fb95f89424b338ee3ce0b007391c02
