### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PrometheusAla** [aDarkDev/NotPixel#54]
Have this error after several minutes of normal work. Please help

[+] 1235: 1 Pixel painted successfully. User new balance: 25.4032
[!] 1235 anti-detect: Sleeping for 4...
[!] 1235: No charge available. Sleeping for 10 minutes...
[+] 1235: 1 Pixel painted successfully. User new balance: 26.4032
[!] 1235 anti-detect: Sleeping for 6...
[!] 1235: No charge available. Sleeping for 10 minutes...
[+] 1235: 1 Pixel painted successfully. User new balance: 27.4032
[!] 1235 anti-detect: Sleeping for 6...
[!] 1235: No charge available. Sleeping for 10 minutes...
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 162, in painter
    charges = NotPxClient.accountStatus()
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 91, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 70, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\client\telegrambaseclient.py", line 487, in loop
    return helpers.get_running_loop()
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-1 (painter)'.
Exception in thread Thread-2 (mine_claimer):
Traceback (most recent call last):
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\helpers.py", line 430, in get_running_loop
    return asyncio.get_running_loop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 211, in mine_claimer
    acc_data = NotPxClient.accountStatus()
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 91, in accountStatus
    return self.request("get","/mining/status","speedPerSecond")
  File "C:\Users\Professional\Downloads\XEmpireBot-main\NotPixel-main\main.py", line 70, in request
    WebAppQuery = self.client.loop.run_until_complete(GetWebAppData(self.client))
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\client\telegrambaseclient.py", line 487, in loop
    return helpers.get_running_loop()
  File "C:\Users\Professional\AppData\Roaming\Python\Python310\site-packages\telethon\helpers.py", line 432, in get_running_loop
    return asyncio.get_event_loop_policy().get_event_loop()
  File "C:\Program Files\Python310\lib\asyncio\events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'Thread-2 (mine_claimer)'.

**Comment by aDarkDev** [comment]
use latest update

**Comment by PrometheusAla** [comment]
I've downloaded it 10 hours ago

**Comment by aDarkDev** [comment]
new update comes 1 hour ago
