### ISSUE TITLE
new pr

### ISSUE THREAD

**Issue by AliCybeRR** [aDarkDev/NotPixel#56]
[!] Timeout Error /mining/claim. Sleeping for 5s...
Exception in thread Thread-12 (mine_claimer):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 230, in mine_claimer
    claimed_count = round(NotPxClient.claim_mining(), 2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 94, in claim_mining
    return self.request("get","/mining/claim","claimed")['claimed']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-8 (mine_claimer):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 230, in mine_claimer
    claimed_count = round(NotPxClient.claim_mining(), 2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 94, in claim_mining
    return self.request("get","/mining/claim","claimed")['claimed']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
Exception in thread Thread-6 (mine_claimer):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 230, in mine_claimer
    claimed_count = round(NotPxClient.claim_mining(), 2)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 94, in claim_mining
    return self.request("get","/mining/claim","claimed")['claimed']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
[!] Timeout Error /repaint/start. Sleeping for 5s...
Exception in thread Thread-11 (painter):
Traceback (most recent call last):
  File "/usr/lib/python3.11/threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.11/threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 177, in painter
    balance = NotPxClient.autoPaintPixel()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alicyberr/Desktop/NotPixel/main.py", line 105, in autoPaintPixel
    return self.request("post","/repaint/start","balance",data)['balance']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by aDarkDev** [comment]
this error fixed in latest source. use it

**Comment by AliCybeRR** [comment]
im using last src bro

**Comment by aDarkDev** [comment]
im using it, i can't see such error. maybe your internet connection have pakcet loss.
i i see error i will fix soon
