### ISSUE TITLE
error after last update

### ISSUE THREAD

**Issue by salehiparviz** [aDarkDev/NotPixel#60]
No problem that  work agian but waiting on Sleeping for 1 hour..
is it possible to use **error handling** to fix it?
[!] translate: No charge available. Sleeping for 10 minutes...
[+] Authentication renewed!
[!] Timeout Error /repaint/start. Sleeping for 5s...
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1776.0_x64__qbz5n2kfra8p0\Lib\threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "D:\python\921\main.py", line 178, in painter
    balance = NotPxClient.autoPaintPixel()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\python\921\main.py", line 105, in autoPaintPixel
    return self.request("post","/repaint/start","balance",data)['balance']
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by salehiparviz** [comment]
that work after few min

**Comment by aDarkDev** [comment]
New Update Released.
