### ISSUE TITLE
Traceback (most recent call last): Error

### ISSUE THREAD

**Issue by lascalifas** [aDarkDev/NotPixel#66]
Exception in thread Thread-1 (painter):
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner    
    self.run()
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\\Desktop\NotPixel-main (1)\NotPixel-main\main.py", line 266, in painter
    if levels_recharge < config.RE_CHARGE_SPEED_MAX and NotPx.UpgradeReChargeSpeed[levels_recharge]['Price'] >= user_balance:
                                                        ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 5
[+] Auto painting started.
Exception in thread Thread-3 (painter):
Traceback (most recent call last):
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 1038, in _bootstrap_inner    
    self.run()
  File "C:\Users\\AppData\Local\Programs\Python\Python311\Lib\threading.py", line 975, in run
    self._target(*self._args, **self._kwargs)
  File "c:\Users\\Desktop\NotPixel-main (1)\NotPixel-main\main.py", line 266, in painter
    if levels_recharge < config.RE_CHARGE_SPEED_MAX and NotPx.UpgradeReChargeSpeed[levels_recharge]['Price'] >= user_balance:

**Comment by aDarkDev** [comment]
use latest
